lanes:
  - name: north_in
    polygon: [[300,20],[420,20],[420,200],[300,200]]
  - name: south_in
    polygon: [[300,460],[420,460],[420,300],[300,300]]
  - name: west_in
    polygon: [[20,220],[200,220],[200,340],[20,340]]
  - name: east_in
    polygon: [[460,220],[300,220],[300,340],[460,340]]
